name: Doc Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build a website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        with:
           python-version: 3.10
        run: |
          pip3 install --user -r requirements.txt

      - name: Deploy
      - uses: peaceiris/actions-gh-pages@v3
        run: | 
          mkdocs gh-deploy 
 
