name: Doc Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # runs at 00:00 UTC every day

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        with:
          python-version: 3.10
        run : |
          python3 -m pip install --upgrage pip 
          pip3 install --user -r requirements.txt
        
      - name: Deploy
        with:
          branch: main
        run: | 
          mkdocs gh-deploy 
 
