name: Doc Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']  # requires python<=3.9
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip3 install --user -r requirements.txt
          git config --global user.email "ttlarva@qq.com"
          git config --global user.name "ttlarva"
        
      - name: Deploy
        run: | 
          git update-index mkdocs gh-deploy 
 
